import type { Metadata } from 'next';

import './globals.css';
import GlobalStyles from '../styles/GlobalStyles';
import { CssVarsProvider } from '@mui/joy';
import theme from './theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalStyles />
      <CssVarsProvider theme={theme}>
        <body>{children}</body>{' '}
      </CssVarsProvider>
    </html>
  );
}
